services:
  onlyoffice:
    image: onlyoffice/documentserver:unlimited-9.0.4-52 # or whatever your tag is
    container_name: onlyoffice
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyofficeuser
      - DB_PWD=your-password
      - AMQP_TYPE=rabbitmq
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=longsecrettoken
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    ports:
      - '8081:80' # I'm using nginx reverse proxy, so I map port 80 to 8081
#      - '443:443'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: always
    volumes:
       - ./log:/var/log/onlyoffice       # logs    
       - ./data:/var/www/onlyoffice/Data # certificates
       - ./filecache:/var/lib/onlyoffice # file cache
    networks:
      - nextcloud
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq:4.1.4
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - nextcloud

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:15
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyofficeuser
      - POSTGRES_PASSWORD=Atm@123456
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql
    command: >
      -c max_connections=250
      -c log_timezone='Asia/Ho_Chi_Minh'
      -c timezone='Asia/Ho_Chi_Minh'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onlyoffice"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - nextcloud

networks:
  nextcloud:
